### ISSUE TITLE
I think ChromeASP is not working now

### ISSUE THREAD

**Issue by PPotera66** [PieterCooreman/ChromeASP#1]
Hello. I also use headless chrome to generate PDF from HTML but I found it is not woking now. It works in command line but it does not on IIS. It adds some amount of Chrome processes but never ends and generates nothing. A tried to find solution and found your pages with your site to check the function. But now I am not able to get PDF or anything from it. Do you know about it and do you know the reason ? Thank you.

**Comment by PieterCooreman** [comment]
Hello @PPotera66  issue confirmed.
Changing --headless to --headless=old fixes the issue
The new headless mode needs other parameters apparently. Not sure which ones exactly. To be sorted out.

**Comment by PPotera66** [comment]
Yes, you are right. I found it 5 minutes after sending the issue. Thank you anyway.

**Comment by PPotera66** [comment]
Did you try chrome-headless-shell ?

**Comment by PieterCooreman** [comment]
No, I use Version 128.0.6613.114 (Official Build) (64-bit)

I also just read about such a stand alone shell version of headless chrome. Have you tried it?

**Comment by PPotera66** [comment]
I have read that old headless version changes to the shell, so I downloaded stable version for win64 and tried the same batch without headless parameter and it works. But I use it only to get PDF from HTML, nothing more, so it is enough for me.

**Comment by PieterCooreman** [comment]
I also downloaded such a headless-shell version on https://googlechromelabs.github.io/chrome-for-testing/

It does the trick. I guess other users will face the same issue now with headless=old/new. The issue started showing as from today. I use ChromeASP in various web applications. 

Thanks for reporting this issue.
